version: "latest"
services: 
  diplo-server:
    image: mysql
    build: . 
    ports: 
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: apple
      MYSQL_DATABASE: movies
  
  admin:
    image: adminer
    ports: 
      - "8080:8080"

  

